handlebars:
  enabled: true
  suffix: .html

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

security:
  jwt:
    token:
      expire-length: 3600000
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno

cloud:
  aws:
    stack:
      auto: false  # 로컬에서 실행시 AWS stack autoconfiguration 수행과정에서 발생하는 에러 방지
    region:
      static: ap-northeast-2
