spring:
  datasource:
    hikari:
      max-lifetime: 58000
    password: masterpw
    url: jdbc:mysql://127.0.0.1:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
    show-sql: true
  config:
    activate:
      on-profile: local

logging:
  level:
    nextstep.subway: debug
