spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    activate:
      on-profile: test

logging:
  level:
    nextstep.subway: debug

cloud:
  aws:
    stack:
      auto: false  # 로컬에서 실행시 AWS stack autoconfiguration 수행과정에서 발생하는 에러 방지
    region:
      static: ap-northeast-2
